-- MySQL Script generated by MySQL Workbench
-- 11/19/16 15:30:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gotrip
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gotrip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gotrip` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema turma_da_monica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema turma_da_monica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `turma_da_monica` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema login_sessao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema login_sessao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `login_sessao` DEFAULT CHARACTER SET latin1 ;
USE `gotrip` ;

-- -----------------------------------------------------
-- Table `gotrip`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gotrip`.`cidade` (
  `id_cidade` INT(8) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `sigla_estado` CHAR(2) NOT NULL COMMENT '',
  PRIMARY KEY (`id_cidade`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gotrip`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gotrip`.`endereco` (
  `id_endereco` INT(8) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `numero` INT(6) NOT NULL COMMENT '',
  `bairro` VARCHAR(45) NOT NULL COMMENT '',
  `cep` INT(8) NOT NULL COMMENT '',
  `id_cidade` INT(8) NOT NULL COMMENT '',
  `complemento` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_endereco`)  COMMENT '',
  INDEX `fk_endereco_Cidade1_idx` (`id_cidade` ASC)  COMMENT '',
  CONSTRAINT `fk_endereco_Cidade1`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `gotrip`.`cidade` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gotrip`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gotrip`.`usuario` (
  `id` INT(8) NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `cpf` VARCHAR(45) NOT NULL COMMENT '',
  `telefone` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `senha` VARCHAR(45) NOT NULL COMMENT '',
  `data_nascimento` DATE NULL COMMENT '',
  `id_endereco` INT(8) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_usuario_endereco2_idx` (`id_endereco` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_endereco2`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `gotrip`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gotrip`.`excursao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gotrip`.`excursao` (
  `id_excursao` INT(8) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `categoria` VARCHAR(45) NULL COMMENT '',
  `local_de_partida` VARCHAR(45) NOT NULL COMMENT '',
  `total_participantes` INT NOT NULL COMMENT '',
  `data_partida` DATE NOT NULL COMMENT '',
  `min_participantes` INT NOT NULL COMMENT '',
  `valor` DECIMAL(7,2) NOT NULL COMMENT '',
  `descricao` TEXT NOT NULL COMMENT '',
  `imagem1` VARCHAR(80) NULL COMMENT '',
  `imagem2` VARCHAR(80) NULL COMMENT '',
  `status` VARCHAR(45) NOT NULL COMMENT '',
  `id_usuario` INT(8) NOT NULL COMMENT '',
  `id_cidade` INT(8) NOT NULL COMMENT '',
  PRIMARY KEY (`id_excursao`)  COMMENT '',
  INDEX `fk_excursao_usuario1_idx` (`id_usuario` ASC)  COMMENT '',
  INDEX `fk_excursao_cidade1_idx` (`id_cidade` ASC)  COMMENT '',
  CONSTRAINT `fk_excursao_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `gotrip`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_excursao_cidade1`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `gotrip`.`cidade` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gotrip`.`participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gotrip`.`participante` (
  `id` INT(8) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `data_nascimento` DATE NOT NULL COMMENT '',
  `cpf` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `telefone` VARCHAR(45) NOT NULL COMMENT '',
  `sexo` CHAR(9) NOT NULL COMMENT '',
  `rg` VARCHAR(45) NOT NULL COMMENT '',
  `status` VARCHAR(45) NOT NULL COMMENT '',
  `id_endereco` INT(8) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_participante_endereco1_idx` (`id_endereco` ASC)  COMMENT '',
  CONSTRAINT `fk_participante_endereco1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `gotrip`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gotrip`.`participante_excursao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gotrip`.`participante_excursao` (
  `id_participantes` INT(8) NOT NULL COMMENT '',
  `id_excursao` INT(8) NOT NULL COMMENT '',
  PRIMARY KEY (`id_participantes`, `id_excursao`)  COMMENT '',
  INDEX `fk_participante_has_excursao_excursao2_idx` (`id_excursao` ASC)  COMMENT '',
  INDEX `fk_participante_has_excursao_participante2_idx` (`id_participantes` ASC)  COMMENT '',
  CONSTRAINT `fk_participante_has_excursao_participante2`
    FOREIGN KEY (`id_participantes`)
    REFERENCES `gotrip`.`participante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante_has_excursao_excursao2`
    FOREIGN KEY (`id_excursao`)
    REFERENCES `gotrip`.`excursao` (`id_excursao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `turma_da_monica` ;

-- -----------------------------------------------------
-- Table `turma_da_monica`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turma_da_monica`.`turmas` (
  `cod_turma` INT(4) NOT NULL COMMENT '',
  `nome` VARCHAR(50) NOT NULL COMMENT '',
  `turno` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`cod_turma`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `turma_da_monica`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turma_da_monica`.`enderecos` (
  `cod_endereco` INT(8) NOT NULL AUTO_INCREMENT COMMENT '',
  `logradouro` VARCHAR(80) NOT NULL COMMENT '',
  `numero` INT(6) NOT NULL COMMENT '',
  `complemento` VARCHAR(80) NOT NULL COMMENT '',
  `bairro` VARCHAR(80) NOT NULL COMMENT '',
  `cep` INT(8) NOT NULL COMMENT '',
  `cidade` VARCHAR(60) NOT NULL COMMENT '',
  `sigla_estado` CHAR(2) NOT NULL COMMENT '',
  PRIMARY KEY (`cod_endereco`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `turma_da_monica`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turma_da_monica`.`alunos` (
  `cod_matricula` INT(8) NOT NULL COMMENT '',
  `nome` VARCHAR(30) NOT NULL COMMENT '',
  `sobrenome` VARCHAR(80) NOT NULL COMMENT '',
  `data_nascimento` DATE NOT NULL COMMENT '',
  `data_matricula` DATE NOT NULL COMMENT '',
  `cod_endereco` INT(8) NULL DEFAULT NULL COMMENT '',
  `cod_turma` INT(4) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`cod_matricula`)  COMMENT '',
  INDEX `cod_endereco_idx` (`cod_endereco` ASC)  COMMENT '',
  INDEX `fk_alunos_turmas1_idx` (`cod_turma` ASC)  COMMENT '',
  CONSTRAINT `cod_turma`
    FOREIGN KEY (`cod_turma`)
    REFERENCES `turma_da_monica`.`turmas` (`cod_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_endereco`
    FOREIGN KEY (`cod_endereco`)
    REFERENCES `turma_da_monica`.`enderecos` (`cod_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `turma_da_monica`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turma_da_monica`.`professores` (
  `cod_matricula` INT(8) NOT NULL COMMENT '',
  `nome` VARCHAR(30) NOT NULL COMMENT '',
  `sobrenome` VARCHAR(30) NOT NULL COMMENT '',
  `data_nascimento` DATE NOT NULL COMMENT '',
  `data_admissao` DATE NOT NULL COMMENT '',
  `cod_endereco` INT(8) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`cod_matricula`)  COMMENT '',
  INDEX `fk_professores_enderecos1_idx1` (`cod_endereco` ASC)  COMMENT '',
  CONSTRAINT `fk_professores_enderecos1`
    FOREIGN KEY (`cod_endereco`)
    REFERENCES `turma_da_monica`.`enderecos` (`cod_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `turma_da_monica`.`aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turma_da_monica`.`aulas` (
  `cod_turma` INT(4) NOT NULL COMMENT '',
  `cod_mat_professores` INT(8) NOT NULL COMMENT '',
  PRIMARY KEY (`cod_turma`, `cod_mat_professores`)  COMMENT '',
  INDEX `fk_turmas_has_professores_professores1_idx` (`cod_mat_professores` ASC)  COMMENT '',
  INDEX `fk_turmas_has_professores_turmas1_idx` (`cod_turma` ASC)  COMMENT '',
  CONSTRAINT `fk_turmas_has_professores_turmas1`
    FOREIGN KEY (`cod_turma`)
    REFERENCES `turma_da_monica`.`turmas` (`cod_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turmas_has_professores_professores1`
    FOREIGN KEY (`cod_mat_professores`)
    REFERENCES `turma_da_monica`.`professores` (`cod_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `login_sessao` ;

-- -----------------------------------------------------
-- Table `login_sessao`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login_sessao`.`login` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `usuario` VARCHAR(45) NOT NULL COMMENT '',
  `senha` VARCHAR(45) NOT NULL COMMENT '',
  `nomeDoUsuario` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
